#!/usr/bin/env python3
"""Analyze 2011 CIBC 1615 PDF extraction for key balances."""

print('=' * 70)
print('2011 CIBC 1615 STATEMENT ANALYSIS (FROM PDF EXTRACTION)')
print('=' * 70)
print()
print('KEY MONTHLY BALANCES:')
print('  April 30, 2011:           -22.44  (OVERDRAFT)')
print('  May 31, 2011:          2,527.80  (RECOVERED)')
print('  June 28, 2011:         2,061.88  (POSITIVE)')
print()
print('KEY OBSERVATIONS:')
print('  1. April 30: Account was OVERDRAFT (-$22.44)')
print('  2. May 31: Account recovered to +$2,527.80 (major recovery!)')
print('  3. June 28: Account balance +$2,061.88')
print()
print('TRANSACTION PATTERNS (APRIL):')
print('  - Multiple NSF charges: $42.50 each (at least 3 found)')
print('  - Multiple "CORRECTION 00339" entries (NSF-related adjustments)')
print('  - Heffner Auto Finance rent/lease payments: $1,475-$2,525')
print('  - Regular gas purchases: CENTEX, FAS GAS, SHELL')
print('  - Merchant credit memo deposits (4017775): VISA, MC, IDP')
print()
print('TRANSACTION PATTERNS (MAY):')
print('  - Starting balance: -$308.31 (overdraft)')
print('  - Two cheques bounced (NSF): Cheque #143, #149')
print('  - Large correction/reversal entries')
print('  - Recovery through merchant deposits and some deposits')
print()
print('TRANSACTION PATTERNS (JUNE):')
print('  - Consistent positive balance')
print('  - Cheque bounces (NSF): Cheque #152, #153, #154')
print('  - Ongoing Heffner Auto Finance payments')
print('  - Regular merchant deposits and business expenses')
print()
print('=' * 70)
print('CRITICAL FINDING FOR 2012 RECONCILIATION:')
print('=' * 70)
print('  Need to see DECEMBER 2011 closing balance to establish')
print('  the CORRECT 2012 OPENING BALANCE for account 1615')
print()
print('  CURRENT STATUS:')
print('    - 2012 is currently MISSING from database (0 transactions)')
print('    - 2013 starts with NULL balances (75 transactions)')
print('    - 2014-2017 have partial NULL balances (28/12/12/12 records)')
print()
print('ACTION ITEMS:')
print('  1. Extract December 2011 from PDF to get 2011 CLOSING balance')
print('  2. That closing balance should be 2012 OPENING balance')
print('  3. Import 2012 data from backup with correct opening balance')
print('  4. Calculate 2013 balances using 2012 closing as opening')
print('  5. Fill in 2014-2017 missing closing balances')
print()
print('BOUNCED CHEQUE HISTORY (FROM 2011 PDF):')
print('  - Cheque #143: Bounced, amount visible')
print('  - Cheque #149: Bounced')
print('  - Cheque #152: NSF charge $42.50 on June 1')
print('  - Cheque #153: Cleared successfully')
print('  - Cheque #154: NSF charge')
print('  - Cheque #155: Cleared successfully')
print()
print('=' * 70)
print('NOTE: OVERDRAFT ACCOUNT CHARACTERISTICS')
print('=' * 70)
print('  Account 1615 is OVERDRAFT-ONLY (per earlier research)')
print('  Branch #4 (Red Deer)')
print('  No regular debit card transactions expected')
print('  Business cheques and pre-authorized payments primary use')
print('  Monthly fees for overdraft maintenance')
print('=' * 70)
