"""
Apply Calendar_0 event details to charter booking notes (idempotent)
====================================================================

Reads `reports/calendar_0_events.json` (generated by extract_calendar_events.py)
and, for events that reference exactly one 6-digit reserve_number, copies the
event details (subject, location, body, start/end) into the `booking_notes`
column of the matching `charters` row.

Rules:
- Exact single reserve match only (len(reserve_numbers) == 1).
- Do not overwrite non-empty notes unless `--force-overwrite` is used.
- Idempotent: if existing notes already equal the computed content, skip.
- Dry-run by default; require `--apply` to write.

Usage:
  python -X utf8 scripts/apply_calendar_notes_to_charters.py \
    --events "l:\\limo\\reports\\calendar_0_events.json" --apply
"""

import argparse
import json
import os
import psycopg2
from datetime import datetime


def get_pg():
    return psycopg2.connect(
        host=os.getenv("DB_HOST", "localhost"),
        database=os.getenv("DB_NAME", "almsdata"),
        user=os.getenv("DB_USER", "postgres"),
        password=os.getenv("DB_PASSWORD", "***REMOVED***"),
    )


def build_note(ev: dict) -> str:
    parts = []
    subj = (ev.get("subject") or "").strip()
    loc = (ev.get("location") or "").strip()
    body = (ev.get("body") or "").strip()
    start = ev.get("start") or ""
    end = ev.get("end") or ""
    if subj:
        parts.append(f"Subject: {subj}")
    if loc:
        parts.append(f"Location: {loc}")
    if start or end:
        parts.append(f"When: {start} → {end}")
    if body:
        parts.append("Details:\n" + body)
    return "\n".join(parts).strip()


def main():
    ap = argparse.ArgumentParser(description="Apply calendar details to charter booking notes")
    ap.add_argument("--events", default=r"l:\\limo\\reports\\calendar_0_events.json", help="Path to calendar events JSON")
    ap.add_argument("--apply", action="store_true", help="Write changes; otherwise dry-run")
    ap.add_argument("--force-overwrite", action="store_true", help="Overwrite non-empty notes")
    ap.add_argument("--show-notes", action="store_true", help="Print the generated note content for each candidate update")
    args = ap.parse_args()

    if not os.path.exists(args.events):
        print(f"Events JSON not found: {args.events}")
        return 2

    with open(args.events, "r", encoding="utf-8") as f:
        data = json.load(f)
    events = data.get("events") or []

    pg = get_pg()
    cur = pg.cursor()

    updated = 0
    skipped_multi = 0
    skipped_missing = 0
    skipped_existing = 0

    for ev in events:
        reserves = ev.get("reserve_numbers") or []
        if len(reserves) != 1:
            skipped_multi += 1
            continue
        rn = reserves[0]

        # Fetch current notes
        cur.execute(
            """
            SELECT charter_id, booking_notes
            FROM charters
            WHERE reserve_number = %s
            LIMIT 1
            """,
            (rn,),
        )
        row = cur.fetchone()
        if not row:
            skipped_missing += 1
            continue
        charter_id, current_notes = row
        new_note = build_note(ev)

        if current_notes and not args.force_overwrite:
            # If identical, skip quietly; otherwise count as existing
            if (current_notes or "").strip() == new_note.strip():
                continue
            skipped_existing += 1
            continue

        if args.apply:
            cur.execute(
                """
                UPDATE charters
                SET booking_notes = %s
                WHERE charter_id = %s
                """,
                (new_note, charter_id),
            )
            updated += cur.rowcount
            if args.show_notes:
                print(f"APPLIED NOTES charter_id={charter_id} reserve={rn} length={len(new_note)}\n-----\n{new_note}\n-----")
        else:
            # Dry-run preview
            print(f"DRY RUN: Would update charter {charter_id} (reserve {rn}) with notes length {len(new_note)}")
            if args.show_notes:
                print(f"PREVIEW NOTES charter_id={charter_id} reserve={rn} length={len(new_note)}\n-----\n{new_note}\n-----")
            updated += 1

    if args.apply:
        pg.commit()
    else:
        pg.rollback()

    print("Summary:")
    print(f"  Candidates processed: {len(events)}")
    print(f"  Updated (or would update): {updated}")
    print(f"  Skipped (multiple/no reserve match): {skipped_multi}")
    print(f"  Skipped (no matching charter): {skipped_missing}")
    print(f"  Skipped (existing notes, not forced): {skipped_existing}")

    cur.close()
    pg.close()


if __name__ == "__main__":
    main()
