#!/usr/bin/env python3
"""
Recalculate GST for receipts assuming Total is tax-included when GST is missing/zero and not exempt.
- Formula: gst_amount = gross_amount * (0.05 / 1.05)
- net_amount is generated by DB if defined; if not, we can optionally set it (skipped by default)
- Updates gst_code to 'G' when gst_amount > 0 else 'Z'
- Skips rows where gst_amount already > 0 or gst_code indicates exempt
- Provides a dry-run option
"""
import os
from datetime import datetime, date
import psycopg2

DB = dict(
    dbname=os.environ.get('DB_NAME', 'almsdata'),
    user=os.environ.get('DB_USER', 'postgres'),
    password=os.environ.get('DB_PASSWORD', '***REMOVED***'),
    host=os.environ.get('DB_HOST', 'localhost'),
    port=int(os.environ.get('DB_PORT', '5432')),
)

EXEMPT_CODES = {'Z','EXCL','EXEMPT','NO GST','GST EXEMPT','GST EXCL'}
RATE = 0.05

def parse_date(s: str | None) -> date | None:
    if not s:
        return None
    s = s.strip()
    for fmt in ("%Y-%m-%d", "%m/%d/%Y"):
        try:
            return datetime.strptime(s, fmt).date()
        except Exception:
            continue
    raise ValueError(f"Could not parse date: {s}")

def main(dry_run: bool = False, from_date: str | None = None, to_date: str | None = None,
         vendor: str | None = None, force_recalc: bool = False):
    conn = psycopg2.connect(**DB)
    try:
        with conn:
            with conn.cursor() as cur:
                # Build WHERE clauses dynamically
                where = ["r.gross_amount IS NOT NULL"]
                params: list = []
                if not force_recalc:
                    where.append("COALESCE(r.gst_amount,0) = 0")
                # Skip explicit exempt codes by default
                where.append("UPPER(COALESCE(r.gst_code,'')) NOT IN %s")
                params.append(tuple(EXEMPT_CODES))
                fd = parse_date(from_date)
                td = parse_date(to_date)
                if fd:
                    where.append("r.receipt_date >= %s")
                    params.append(fd)
                if td:
                    where.append("r.receipt_date <= %s")
                    params.append(td)
                if vendor:
                    where.append("r.vendor_name ILIKE %s")
                    params.append(f"%{vendor}%")

                where_sql = " AND ".join(where) if where else "TRUE"

                # Count candidates
                cur.execute(
                    f"SELECT COUNT(*) FROM receipts r WHERE {where_sql}",
                    tuple(params)
                )
                total = cur.fetchone()[0]
                print(f"Candidates to update: {total}")
                if total == 0:
                    return

                if dry_run:
                    # Show a small sample of recalculated values
                    cur.execute(
                        f"""
                        SELECT r.id, r.gross_amount,
                               ROUND(r.gross_amount * (%s / (1+%s)), 2) AS new_gst,
                               COALESCE(r.gst_amount,0) as old_gst,
                               r.vendor_name, r.receipt_date
                          FROM receipts r
                         WHERE {where_sql}
                         ORDER BY r.id
                         LIMIT 10
                        """,
                        tuple([RATE, RATE] + params)
                    )
                    rows = cur.fetchall()
                    for r in rows:
                        print(f"id={r[0]} date={r[5]} vendor={r[4]!r} gross={r[1]} old_gst={r[3]} -> new_gst={r[2]}")
                    return

                # Perform update
                set_clause = (
                    "gst_amount = ROUND(r.gross_amount * (%s / (1+%s)), 2), "
                    "gst_code   = CASE WHEN ROUND(r.gross_amount * (%s / (1+%s)), 2) > 0 THEN 'G' ELSE 'Z' END"
                )
                update_params = [RATE, RATE, RATE, RATE]
                sql = f"UPDATE receipts r SET {''.join(set_clause)} WHERE {where_sql}"
                cur.execute(sql, tuple(update_params + params))
                print(f"Updated rows: {cur.rowcount}")
    finally:
        conn.close()

if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser(description='Backfill receipts GST as tax-included (5%)')
    p.add_argument('--dry-run', action='store_true', help='Show sample changes only, do not update')
    p.add_argument('--from', dest='from_date', help='Start date (YYYY-MM-DD or MM/DD/YYYY)')
    p.add_argument('--to', dest='to_date', help='End date (YYYY-MM-DD or MM/DD/YYYY)')
    p.add_argument('--vendor', dest='vendor', help='Vendor name contains (case-insensitive)')
    p.add_argument('--force-recalc', action='store_true', help='Recalculate GST even if a non-zero value exists (still skips exempt)')
    args = p.parse_args()
    main(dry_run=args.dry_run, from_date=args.from_date, to_date=args.to_date, vendor=args.vendor, force_recalc=args.force_recalc)
