CREATE USER IF NOT EXISTS alms WITH PASSWORD 'alms_secure_password_2024';
GRANT CONNECT ON DATABASE almsdata TO alms;
GRANT USAGE ON SCHEMA public TO alms;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO alms;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO alms;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO alms;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO alms;
SELECT usename FROM pg_user WHERE usename='alms';
