#!/usr/bin/env python3
"""
Comprehensive UI Element Testing Report
Generates a report of all testable elements discovered in the desktop app.
"""

import sys
import json
from pathlib import Path
from collections import defaultdict

print("📊 COMPREHENSIVE UI TESTING REPORT")
print("="*80)

# Read the inventory file generated by inventory_ui_elements.py
inventory_file = Path('l:\\limo\\element_inventory.json')

if not inventory_file.exists():
    print("❌ Element inventory not found. Run inventory_ui_elements.py first.")
    print(f"   Expected file: {inventory_file}")
    sys.exit(1)

with open(inventory_file, 'r', encoding='utf-8') as f:
    inventory = json.load(f)

# Calculate statistics
total_buttons = len(inventory.get('buttons', []))
total_actions = len(inventory.get('menu_actions', []))
total_inputs = len(inventory.get('text_inputs', []))
total_areas = len(inventory.get('text_areas', []))
total_dropdowns = len(inventory.get('dropdowns', []))
total_checkboxes = len(inventory.get('checkboxes', []))
total_spinners = len(inventory.get('spinners_int', [])) + len(inventory.get('spinners_float', []))
total_tables = len(inventory.get('tables', []))
total_tabs = len(inventory.get('tab_widgets', []))
total_calendars = len(inventory.get('calendars', []))
total_dates = len(inventory.get('date_inputs', []))
total_times = len(inventory.get('time_inputs', []))
total_sliders = len(inventory.get('sliders', []))
total_labels = len(inventory.get('labels', []))

total_interactive = (
    total_buttons + total_actions + total_inputs + total_areas + 
    total_dropdowns + total_checkboxes + total_spinners + total_tables +
    total_tabs + total_calendars + total_dates + total_times + total_sliders
)

print(f"\n🔘 BUTTONS: {total_buttons}")
enabled_buttons = sum(1 for b in inventory.get('buttons', []) if b.get('enabled'))
print(f"   ✅ Enabled: {enabled_buttons}")
print(f"   ✓ Testable buttons (click): {enabled_buttons}")

print(f"\n📋 MENU ACTIONS: {total_actions}")
enabled_actions = sum(1 for a in inventory.get('menu_actions', []) if a.get('enabled'))
print(f"   ✅ Enabled: {enabled_actions}")
print(f"   ✓ Testable actions (trigger): {enabled_actions}")

print(f"\n⌨️  TEXT INPUTS: {total_inputs}")
enabled_inputs = sum(1 for i in inventory.get('text_inputs', []) if i.get('enabled') and not i.get('readonly'))
print(f"   ✅ Enabled & Writable: {enabled_inputs}")
print(f"   ✓ Testable inputs (set value): {enabled_inputs}")

print(f"\n📝 TEXT AREAS: {total_areas}")
enabled_areas = sum(1 for a in inventory.get('text_areas', []) if a.get('enabled') and not a.get('readonly'))
print(f"   ✅ Enabled & Writable: {enabled_areas}")

print(f"\n🔽 DROPDOWNS: {total_dropdowns}")
enabled_dropdowns = sum(1 for d in inventory.get('dropdowns', []) if d.get('enabled') and d.get('items_count', 0) > 1)
print(f"   ✅ Enabled with items: {enabled_dropdowns}")
print(f"   ✓ Testable dropdowns (select): {enabled_dropdowns}")

print(f"\n☑️  CHECKBOXES: {total_checkboxes}")
enabled_checkboxes = sum(1 for c in inventory.get('checkboxes', []) if c.get('enabled'))
print(f"   ✅ Enabled: {enabled_checkboxes}")
print(f"   ✓ Testable checkboxes (toggle): {enabled_checkboxes}")

print(f"\n🔢 SPINNERS: {total_spinners}")
enabled_spinners = sum(1 for s in inventory.get('spinners_int', []) + inventory.get('spinners_float', []) if s.get('enabled'))
print(f"   ✅ Enabled: {enabled_spinners}")
print(f"   ✓ Testable spinners (increment): {enabled_spinners}")

print(f"\n📊 TABLES: {total_tables}")
print(f"   ✓ Testable tables (select rows): {total_tables}")

print(f"\n📑 TABS: {total_tabs}")
print(f"   ✓ Testable tab widgets (switch): {total_tabs}")

print(f"\n📅 CALENDARS: {total_calendars}")
print(f"   ✓ Testable calendars: {total_calendars}")

print(f"\n📆 DATE INPUTS: {total_dates}")
print(f"\n⏰ TIME INPUTS: {total_times}")

print(f"\n🎚️  SLIDERS: {total_sliders}")

print("\n" + "="*80)
print("📈 TEST COVERAGE SUMMARY")
print("="*80)

# Estimate pass rate based on enabled elements
testable_buttons = enabled_buttons
testable_actions = enabled_actions
testable_inputs = enabled_inputs
testable_dropdowns = enabled_dropdowns
testable_checkboxes = enabled_checkboxes
testable_spinners = enabled_spinners
testable_tables = total_tables
testable_tabs = total_tabs

estimated_testable = (
    testable_buttons + testable_actions + testable_inputs + 
    testable_dropdowns + testable_checkboxes + testable_spinners +
    testable_tables + testable_tabs
)

print(f"\n✓ TOTAL TESTABLE ELEMENTS: {estimated_testable}")
print(f"  • Buttons to click: {testable_buttons}")
print(f"  • Menu actions to trigger: {testable_actions}")
print(f"  • Text inputs to fill: {testable_inputs}")
print(f"  • Dropdowns to select: {testable_dropdowns}")
print(f"  • Checkboxes to toggle: {testable_checkboxes}")
print(f"  • Spinners to adjust: {testable_spinners}")
print(f"  • Tables to interact with: {testable_tables}")
print(f"  • Tab widgets to switch: {testable_tabs}")

print(f"\n📊 TOTAL INTERACTIVE ELEMENTS: {total_interactive}")
print(f"   Buttons, menus, inputs, dropdowns, checkboxes, spinners,")
print(f"   tables, tabs, calendars, date/time inputs, sliders")

print(f"\n🏷️  LABELS/DISPLAY ELEMENTS: {total_labels}")
print(f"   (Not directly testable but provide UI structure)")

# Estimate coverage
coverage_pct = (estimated_testable / total_interactive * 100) if total_interactive > 0 else 0
print(f"\n📈 ESTIMATED COVERAGE: {coverage_pct:.1f}%")
print(f"   (Based on enabled/interactive elements)")

print("\n" + "="*80)
print("✅ TEST STRATEGY")
print("="*80)

strategies = [
    ("🔘 BUTTONS", [
        f"Click all {testable_buttons} enabled buttons",
        "Verify no crashes or unhandled exceptions",
        "Check for dialogs, which will be auto-closed"
    ]),
    ("📋 MENU ACTIONS", [
        f"Trigger all {testable_actions} menu actions",
        "Verify menu items are responsive",
        "Check for submenu navigation"
    ]),
    ("⌨️  TEXT INPUTS", [
        f"Test all {testable_inputs} writable text fields",
        "Enter test values and verify acceptance",
        "Check character limits and validation"
    ]),
    ("🔽 DROPDOWNS", [
        f"Test all {testable_dropdowns} enabled dropdowns",
        "Select different options and verify UI updates",
        "Verify cascading dropdowns work"
    ]),
    ("☑️  CHECKBOXES", [
        f"Toggle all {testable_checkboxes} checkboxes",
        "Verify state changes are reflected in UI",
        "Check dependent controls enable/disable"
    ]),
    ("🔢 SPINNERS", [
        f"Test all {testable_spinners} spinners",
        "Increment and decrement values",
        "Verify min/max bounds are respected"
    ]),
    ("📊 TABLES", [
        f"Test all {testable_tables} tables",
        "Select rows and columns",
        "Verify sorting and filtering if available"
    ]),
    ("📑 TABS", [
        f"Switch between all {testable_tabs} tabs",
        "Verify content loads correctly",
        "Check for performance issues"
    ])
]

for section, details in strategies:
    print(f"\n{section}")
    for detail in details:
        print(f"  • {detail}")

print("\n" + "="*80)
print("🚀 TO RUN AUTOMATED TESTS")
print("="*80)
print("""
1. Start the desktop app:
   cd l:\\limo && .\.venv\Scripts\python.exe -X utf8 desktop_app\main.py

2. Run the inventory scanner:
   .\.venv\Scripts\python.exe -X utf8 scripts\inventory_ui_elements.py

3. Run this test report:
   .\.venv\Scripts\python.exe -X utf8 scripts\test_ui_elements.py

4. Run manual UI tests:
   • Click each button systematically
   • Test all dropdown selections
   • Fill in text fields with valid and invalid data
   • Toggle checkboxes and verify behavior
   • Switch between tabs
   • Test print/save/export features
   • Test delete operations with confirmation dialogs

5. Check logs for errors:
   search for error logs in desktop_app/
""")

print("\n" + "="*80)
print(f"Report generated: {Path(__file__).name}")
print("="*80 + "\n")

# Export summary
summary = {
    'total_buttons': total_buttons,
    'testable_buttons': testable_buttons,
    'total_actions': total_actions,
    'testable_actions': testable_actions,
    'total_inputs': total_inputs,
    'testable_inputs': testable_inputs,
    'total_dropdowns': total_dropdowns,
    'testable_dropdowns': testable_dropdowns,
    'total_checkboxes': total_checkboxes,
    'testable_checkboxes': testable_checkboxes,
    'total_spinners': total_spinners,
    'testable_spinners': testable_spinners,
    'total_tables': total_tables,
    'total_tabs': total_tabs,
    'estimated_testable': estimated_testable,
    'total_interactive': total_interactive,
    'coverage_percentage': coverage_pct
}

summary_file = Path('l:\\limo\\reports') / 'ui_test_summary.json'
summary_file.parent.mkdir(parents=True, exist_ok=True)

with open(summary_file, 'w', encoding='utf-8') as f:
    json.dump(summary, f, indent=2)

print(f"✅ Summary exported to {summary_file}\n")
