--
-- PostgreSQL database dump
--

\restrict VhLPfglanHthBYxpEeh9bGgZsCyNaY0SsOT8FkvJ2l1HK4qNxlPdZ22Jroybbbi

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chart_of_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chart_of_accounts (
    account_code character varying(10) NOT NULL,
    parent_account character varying(10),
    account_name character varying(200) NOT NULL,
    account_type character varying(50) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    qb_account_type character varying(50),
    account_level integer DEFAULT 0,
    is_header_account boolean DEFAULT false,
    normal_balance character varying(10),
    current_balance numeric(15,2) DEFAULT 0,
    bank_account_number text,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_tax_applicable boolean DEFAULT false,
    is_business_expense boolean DEFAULT true,
    is_linked_account boolean DEFAULT false,
    requires_vehicle boolean DEFAULT false,
    requires_employee boolean DEFAULT false,
    default_category_code character varying(50),
    CONSTRAINT chart_of_accounts_normal_balance_check CHECK (((normal_balance)::text = ANY (ARRAY[('DEBIT'::character varying)::text, ('CREDIT'::character varying)::text])))
);


--
-- Data for Name: chart_of_accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1020', '1000', 'Savings Account', 'Asset', 'Sub-account of Cash and Cash Equivalents', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1030', '1000', 'Petty Cash', 'Asset', 'Sub-account of Cash and Cash Equivalents', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1040', '1000', 'Money Market', 'Asset', 'Sub-account of Cash and Cash Equivalents', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1530', '1500', 'Accumulated Depreciation', 'Asset', 'Sub-account of Fixed Assets', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2130', '2100', 'Line of Credit', 'Liability', 'Sub-account of Loans Payable', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4020', '4000', 'Airport Transfers', 'Revenue', 'Sub-account of Service Revenue', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4030', '4000', 'Special Events', 'Revenue', 'Sub-account of Service Revenue', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4040', '4000', 'Other Services', 'Revenue', 'Sub-account of Service Revenue', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5010', '5000', 'Driver Wages', 'COGS', 'Sub-account of Direct Operating Costs', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5020', '5000', 'Commissions', 'COGS', 'Sub-account of Direct Operating Costs', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1000', NULL, 'Assets', 'Asset', 'All company assets', true, '2025-10-20 12:32:50.673029', 'OtherCurrentAsset', 0, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1010', '1000', 'Cash & Bank Accounts', 'Asset', 'All cash and banking accounts', true, '2025-10-20 12:32:50.673029', 'Bank', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1011', '1010', 'CIBC Checking 0228362', 'Asset', 'Primary operating account', true, '2025-11-26 21:37:40.578532', 'Bank', 2, false, 'DEBIT', 0.00, '0228362', '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1012', '1010', 'Scotia Bank 903990106011', 'Asset', 'Secondary business account', true, '2025-11-26 21:37:40.578532', 'Bank', 2, false, 'DEBIT', 0.00, '903990106011', '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1015', '1010', 'Petty Cash', 'Asset', 'Cash box for driver floats and reimbursements', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1016', '1010', 'Driver Float Outstanding', 'Asset', 'Cash floats issued to drivers', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1018', '1010', 'Undeposited Funds', 'Asset', 'Cash and checks awaiting deposit', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1200', '1000', 'Prepaid Expenses', 'Asset', 'Expenses paid in advance', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1201', '1200', 'Prepaid Insurance', 'Asset', 'Insurance premiums paid in advance', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1202', '1200', 'Prepaid Rent', 'Asset', 'Rent paid in advance', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1203', '1200', 'Prepaid Licenses & Permits', 'Asset', 'Annual licenses and permits prepaid', true, '2025-11-26 21:37:40.578532', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1400', '1000', 'Fixed Assets - Vehicles', 'Asset', 'Limousine fleet assets', true, '2025-11-26 21:37:40.578532', 'FixedAsset', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1410', '1400', 'Vehicles - Cost', 'Asset', 'Original cost of all vehicles', true, '2025-11-26 21:37:40.578532', 'FixedAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1420', '1400', 'Vehicles - Accumulated Depreciation', 'Asset', 'Contra-asset: accumulated depreciation on fleet', true, '2025-11-26 21:37:40.578532', 'FixedAsset', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1500', '1000', 'Fixed Assets - Equipment', 'Asset', 'Office and business equipment', true, '2025-10-20 12:32:50.673029', 'FixedAsset', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1510', '1500', 'Office Equipment - Cost', 'Asset', 'Computers, furniture, etc.', true, '2025-10-20 12:32:50.673029', 'FixedAsset', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1520', '1500', 'Office Equipment - Accumulated Depreciation', 'Asset', 'Contra-asset: accumulated depreciation on equipment', true, '2025-10-20 12:32:50.673029', 'FixedAsset', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2000', NULL, 'Liabilities', 'Liability', 'All company liabilities', true, '2025-10-20 12:32:50.673029', 'OtherCurrentLiability', 0, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2100', '2000', 'Credit Cards', 'Liability', 'Credit card liabilities', true, '2025-10-20 12:32:50.673029', 'CreditCard', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2110', '2100', 'Amex Business Card', 'Liability', 'American Express business card', true, '2025-10-20 12:32:50.673029', 'CreditCard', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2120', '2100', 'Visa Business Card', 'Liability', 'Visa business card', true, '2025-10-20 12:32:50.673029', 'CreditCard', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2200', '2000', 'Vehicle Loans & Leases', 'Liability', 'Vehicle financing and leases', true, '2025-11-26 21:37:40.578532', 'LongTermLiability', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2220', '2200', 'Vehicle Operating Leases', 'Liability', 'Operating leases for fleet', true, '2025-11-26 21:37:40.578532', 'LongTermLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2300', '2000', 'Payroll Liabilities', 'Liability', 'Payroll taxes and deductions', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2420', '2400', 'GST/HST Paid on Purchases', 'Liability', 'Input tax credits - GST paid on expenses', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1110', '1100', 'Trade Receivables', 'Asset', 'Sub-account of Accounts Receivable', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1120', '1100', 'Other Receivables', 'Asset', 'Sub-account of Accounts Receivable', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2020', '2000', 'Other Payables', 'Liability', 'Sub-account of Accounts Payable', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1100', '1000', 'Accounts Receivable', 'Asset', 'Customer invoices outstanding', true, '2025-10-20 12:32:50.673029', 'AccountsReceivable', 1, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2010', '2000', 'Accounts Payable', 'Liability', 'Vendor bills outstanding', true, '2025-10-20 12:32:50.673029', 'AccountsPayable', 1, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2310', '2300', 'Payroll Taxes Payable - CPP', 'Liability', 'Canada Pension Plan payable', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('3000', NULL, 'Equity', 'Equity', 'Owner equity accounts', true, '2025-10-20 12:32:50.673029', 'Equity', 0, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, false, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('3010', '3000', 'Owner''s Capital', 'Equity', 'Owner investment in business', true, '2025-10-20 12:32:50.673029', 'Equity', 1, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, false, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('3020', '3000', 'Owner''s Draw', 'Equity', 'Owner withdrawals from business', true, '2025-10-20 12:32:50.673029', 'Equity', 1, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, false, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('3030', '3000', 'Retained Earnings', 'Equity', 'Accumulated profits/losses', true, '2025-10-20 12:32:50.673029', 'Equity', 1, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, false, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1013', '1010', 'CIBC Merchant Processing 3648117', 'Asset', 'Credit card merchant deposits - Square/Moneris batch settlements', true, '2025-11-26 21:59:40.605328', 'Bank', 2, false, 'DEBIT', 0.00, '3648117', '2025-11-26 21:59:40.605328', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2210', '2200', 'Heffner Auto Finance', 'Liability', 'Vehicle financing and equipment loans - CIBC account 8314462', true, '2025-11-26 21:37:40.578532', 'LongTermLiability', 2, false, 'CREDIT', 0.00, '8314462', '2025-11-26 21:59:40.605328', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('1135', '1100', 'Prepaid Visa Cards', 'Asset', 'MoneyMart prepaid Visa card balances - Asset account for card loads', true, '2026-01-01 23:27:17.769977', 'OtherCurrentAsset', 2, false, 'DEBIT', 0.00, NULL, '2026-01-01 23:27:17.769977', false, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5330', '5300', 'Property Insurance', 'Expense', 'Sub-account of Insurance', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5540', '5500', 'Subscriptions', 'Expense', 'Sub-account of Office and Administrative', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5740', '5700', 'Parking and Tolls', 'Expense', 'Sub-account of Travel and Entertainment', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5900', NULL, 'Other Operating Expenses', 'Expense', 'Main account: Other Operating Expenses', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5910', '5900', 'Licenses and Permits', 'Expense', 'Sub-account of Other Operating Expenses', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5920', '5900', 'Dues and Subscriptions', 'Expense', 'Sub-account of Other Operating Expenses', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5930', '5900', 'Miscellaneous', 'Expense', 'Sub-account of Other Operating Expenses', true, '2025-10-20 12:32:50.673029', NULL, 0, false, NULL, 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4000', NULL, 'Income', 'Income', 'All revenue sources', true, '2025-10-20 12:32:50.673029', 'Income', 0, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4010', '4000', 'Charter Revenue', 'Income', 'Limousine service revenue', true, '2025-10-20 12:32:50.673029', 'Income', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4011', '4010', 'Hourly Charter Revenue', 'Income', 'Hourly charter bookings', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4012', '4010', 'Airport Transfer Revenue', 'Income', 'Airport pickup/dropoff services', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4013', '4010', 'Package Rate Revenue', 'Income', 'Special event packages (weddings, proms, etc.)', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4014', '4010', 'Extra Time Revenue', 'Income', 'Overtime charges', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4100', '4000', 'Additional Revenue', 'Income', 'Other income sources', true, '2025-10-20 12:32:50.673029', 'Income', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4110', '4100', 'Gratuities', 'Income', 'Tips and gratuities (GST-exempt)', true, '2025-10-20 12:32:50.673029', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4115', '4100', 'Beverage Service Charges', 'Income', 'Charges to customers for beverages provided (compare to 5310 cost)', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4120', '4100', 'Fuel Surcharge Income', 'Income', 'Fuel surcharges passed to customers', true, '2025-10-20 12:32:50.673029', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4130', '4100', 'Late Cancellation Fees', 'Income', 'Cancellation and no-show fees', true, '2025-10-20 12:32:50.673029', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4135', '4100', 'Trade of Services - Income', 'Income', 'Fair market value of services received in trade (e.g., Fibrenew rent)', true, '2025-11-26 21:37:40.578532', 'Income', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('4140', '4100', 'Interest Income', 'Income', 'Bank interest earned', true, '2025-11-26 21:37:40.578532', 'OtherIncome', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5000', NULL, 'Expenses', 'Expense', 'All business expenses', true, '2025-10-20 12:32:50.673029', 'Expense', 0, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5100', '5000', 'Vehicle Operating Expenses', 'Expense', 'Fleet operation costs', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5110', '5100', 'Fuel Expense', 'Expense', 'Gasoline and diesel fuel', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5120', '5100', 'Vehicle Maintenance & Repairs', 'Expense', 'Oil changes, repairs, parts', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5130', '5100', 'Vehicle Insurance', 'Expense', 'Commercial vehicle insurance', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5140', '5100', 'Vehicle Licenses & Permits', 'Expense', 'Registration, permits, inspections', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5150', '5100', 'Vehicle Lease Payments', 'Expense', 'Operating lease payments', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5160', '5100', 'Vehicle Loan Interest', 'Expense', 'Interest on vehicle financing', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5170', '5100', 'Vehicle Depreciation', 'Expense', 'Depreciation expense on fleet', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5200', '5000', 'Driver & Payroll Expenses', 'Expense', 'Labor costs', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5210', '5200', 'Driver Wages', 'Expense', 'Chauffeur wages and commissions', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5220', '5200', 'Employee Wages - Office', 'Expense', 'Office staff salaries', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5230', '5200', 'Payroll Taxes - CPP', 'Expense', 'Employer CPP contributions', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5240', '5200', 'Payroll Taxes - EI', 'Expense', 'Employer EI contributions', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5250', '5200', 'WCB Premiums', 'Expense', 'Workers Compensation premiums', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5300', '5000', 'Customer Service Expenses', 'Expense', 'Customer amenities and hospitality', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5310', '5300', 'Beverages - Customer Service', 'Expense', 'Water, pop, chips purchased for limousine service (compare to revenue recovery)', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5315', '5300', 'Beverages - Business Entertainment', 'Expense', 'Bar/liquor purchases for business meetings, client entertainment (50% deductible)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5320', '5300', 'Driver Meals - On Duty', 'Expense', 'Meals for drivers during charter shifts (business expense)', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5325', '5300', 'Business Meals & Entertainment', 'Expense', 'Client dinners, prospect meetings, networking events (50% deductible CRA)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5400', '5000', 'Office & Administrative', 'Expense', 'Office operating costs', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5410', '5400', 'Rent Expense', 'Expense', 'Office/garage rent', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5420', '5400', 'Office Supplies', 'Expense', 'Stationery, printer supplies, etc.', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5430', '5400', 'Telephone & Internet', 'Expense', 'Phone and internet services', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5440', '5400', 'Utilities', 'Expense', 'Electricity, gas, water', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5450', '5400', 'Equipment Depreciation', 'Expense', 'Office equipment depreciation', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5500', '5000', 'Professional Services', 'Expense', 'Professional fees', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5510', '5500', 'Accounting & Bookkeeping', 'Expense', 'Accountant and bookkeeper fees', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5520', '5500', 'Legal Fees', 'Expense', 'Attorney fees', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5530', '5500', 'Consulting Fees', 'Expense', 'Business consulting', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5600', '5000', 'Marketing & Advertising', 'Expense', 'Marketing and promotional expenses', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5610', '5600', 'Advertising', 'Expense', 'Print, digital, radio ads', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5620', '5600', 'Website & Online Marketing', 'Expense', 'Website hosting, SEO, social media', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5630', '5600', 'Promotional Materials', 'Expense', 'Business cards, brochures, signage', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5640', '5600', 'Promotional Gifts & Giveaways', 'Expense', 'Client gifts, promotional items, referral incentives', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5650', '5600', 'Charitable Donations - Business', 'Expense', 'Donations for community relations, event sponsorships (tax receipts issued)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5660', '5600', 'Trade of Services', 'Expense', 'Charter services traded for goods/services (FMV basis - e.g., Fibrenew rent exchange)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5700', '5000', 'Banking & Financial', 'Expense', 'Banking and financial costs', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5710', '5700', 'Bank Fees & Service Charges', 'Expense', 'Monthly fees, transaction fees', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5720', '5700', 'Credit Card Processing Fees', 'Expense', 'Merchant fees for card payments', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5730', '5700', 'Interest Expense', 'Expense', 'Non-vehicle loan interest', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5800', '5000', 'Other Business Expenses', 'Expense', 'Miscellaneous and grey-area business expenses', true, '2025-10-20 12:32:50.673029', 'Expense', 1, true, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5810', '5800', 'Uniforms & Laundry', 'Expense', 'Driver uniforms and cleaning', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5820', '5800', 'Training & Development', 'Expense', 'Driver training, certifications, safety courses', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5830', '5800', 'Subscriptions & Memberships', 'Expense', 'Software subscriptions, association dues, business networks', true, '2025-10-20 12:32:50.673029', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5840', '5800', 'Business Development Expenses', 'Expense', 'Networking events, industry conferences, business relationship building', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5850', '5800', 'Mixed-Use Expenses', 'Expense', 'Expenses with business AND personal use (track allocation % for CRA)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5860', '5800', 'Supplies - General Business', 'Expense', 'Business supplies not classified elsewhere (cleaning, tools, etc.)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5870', '5800', 'Miscellaneous Business Expense', 'Expense', 'Uncategorized business expenses (review quarterly)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5116', NULL, 'Client Amenities - Food, Coffee, Supplies', 'Expense', 'Food, coffee, balloons, and other amenities provided to charter clients', true, '2026-01-05 15:20:03.60718', NULL, 0, false, NULL, 0.00, NULL, '2026-01-05 15:20:03.60718', true, true, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2320', '2300', 'Payroll Taxes Payable - EI', 'Liability', 'Employment Insurance payable', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2330', '2300', 'Payroll Taxes Payable - Income Tax', 'Liability', 'Federal/provincial income tax withheld', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2340', '2300', 'WCB Payable', 'Liability', 'Workers Compensation Board premiums', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2400', '2000', 'Sales Tax Payable', 'Liability', 'GST/HST collected from customers', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 1, true, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2410', '2400', 'GST/HST Payable', 'Liability', 'GST/HST collected from customers', true, '2025-11-26 21:37:40.578532', 'OtherCurrentLiability', 2, false, 'CREDIT', 0.00, NULL, '2025-11-26 21:37:40.578532', false, true, true, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('5880', '5800', 'Owner Personal (Non-Deductible)', 'Expense', 'Personal expenses paid through business (move to Owner Draw quarterly)', true, '2025-11-26 21:37:40.578532', 'Expense', 2, false, 'DEBIT', 0.00, NULL, '2025-11-26 21:37:40.578532', true, false, false, false, false, NULL);
INSERT INTO public.chart_of_accounts (account_code, parent_account, account_name, account_type, description, is_active, created_at, qb_account_type, account_level, is_header_account, normal_balance, current_balance, bank_account_number, updated_at, is_tax_applicable, is_business_expense, is_linked_account, requires_vehicle, requires_employee, default_category_code) VALUES ('2910', NULL, 'ShareHolder Loan', 'Liability', NULL, true, '2026-02-08 10:47:48.368008', NULL, 0, false, NULL, 0.00, NULL, '2026-02-08 10:47:48.368008', false, true, false, false, false, NULL);


--
-- Name: chart_of_accounts chart_of_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chart_of_accounts
    ADD CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (account_code);


--
-- Name: idx_chart_accounts_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chart_accounts_active ON public.chart_of_accounts USING btree (is_active);


--
-- Name: idx_chart_accounts_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chart_accounts_code ON public.chart_of_accounts USING btree (account_code);


--
-- Name: idx_chart_accounts_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chart_accounts_parent ON public.chart_of_accounts USING btree (parent_account);


--
-- Name: idx_chart_accounts_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chart_accounts_type ON public.chart_of_accounts USING btree (account_type);


--
-- PostgreSQL database dump complete
--

\unrestrict VhLPfglanHthBYxpEeh9bGgZsCyNaY0SsOT8FkvJ2l1HK4qNxlPdZ22Jroybbbi

