#!/usr/bin/env python3
"""
Apply receipt-to-charter linkage by updating receipts table with charter_id and reserve_number
from the matched CSV report generated by match_receipts_to_charters_and_drivers.py
"""
import os
import csv
import sys
import psycopg2

DB_HOST = os.environ.get("DB_HOST", "localhost")
DB_NAME = os.environ.get("DB_NAME", "almsdata")
DB_USER = os.environ.get("DB_USER", "postgres")
DB_PASSWORD = os.environ.get("DB_PASSWORD", os.environ.get("DB_PASSWORD"))

REPORT_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
MATCHED_CSV = os.path.join(REPORT_DIR, "receipt_charter_driver_matches.csv")

def main():
    apply_mode = ('--apply' in sys.argv or '--yes' in sys.argv)
    dry_run = ('--dry-run' in sys.argv)
    if not os.path.exists(MATCHED_CSV):
        print(f"ERROR: Matched CSV not found: {MATCHED_CSV}")
        print("Run match_receipts_to_charters_and_drivers.py first!")
        return
    
    conn = psycopg2.connect(
        host=DB_HOST, database=DB_NAME, user=DB_USER, password=DB_PASSWORD
    )
    cur = conn.cursor()
    
    # Read matched CSV
    print(f"Reading matches from: {MATCHED_CSV}")
    matches = []
    with open(MATCHED_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            receipt_id = int(row["receipt_id"])
            reserve_number = row["reserve_number_matched"] if row["reserve_number_matched"] else None
            charter_id = int(row["charter_id_matched"]) if row["charter_id_matched"] else None
            employee_id = int(row["driver_match_id"]) if row["driver_match_id"] else None
            
            matches.append({
                "receipt_id": receipt_id,
                "reserve_number": reserve_number,
                "charter_id": charter_id,
                "employee_id": employee_id
            })
    
    print(f"Loaded {len(matches):,} matched receipts from CSV")
    
    # Preview current state
    print("\nChecking current linkage state in database...")
    cur.execute("""
        SELECT 
            COUNT(*) as total,
            SUM(CASE WHEN charter_id IS NOT NULL THEN 1 ELSE 0 END) as has_charter_id,
            SUM(CASE WHEN reserve_number IS NOT NULL THEN 1 ELSE 0 END) as has_reserve_number,
            SUM(CASE WHEN employee_id IS NOT NULL THEN 1 ELSE 0 END) as has_employee_id
        FROM receipts
        WHERE revenue > 0
    """)
    r = cur.fetchone()
    print(f"Current state: {r[0]:,} revenue receipts")
    print(f"  - With charter_id: {r[1]:,}")
    print(f"  - With reserve_number: {r[2]:,}")
    print(f"  - With employee_id: {r[3]:,}")
    
    # Apply updates
    print("\n" + "="*80)
    if not apply_mode:
        print(f"Dry-run: would apply {len(matches):,} updates to receipts. Pass --apply to execute.")
        cur.close()
        conn.close()
        return
    
    print("\nApplying linkages...")
    reserve_updates = 0
    charter_updates = 0
    employee_updates = 0
    
    for match in matches:
        receipt_id = match["receipt_id"]
        reserve_number = match["reserve_number"]
        charter_id = match["charter_id"]
        employee_id = match["employee_id"]
        
        # Get current values
        cur.execute("""
            SELECT reserve_number, charter_id, employee_id
            FROM receipts
            WHERE receipt_id = %s
        """, (receipt_id,))
        current = cur.fetchone()
        
        if not current:
            print(f"WARNING: Receipt {receipt_id} not found in database!")
            continue
        
        current_reserve, current_charter, current_employee = current
        
        # Only update if we have a match and current value is NULL
        updates = []
        values = []
        
        if reserve_number and not current_reserve:
            updates.append("reserve_number = %s")
            values.append(reserve_number)
            reserve_updates += 1
        
        if charter_id and not current_charter:
            updates.append("charter_id = %s")
            values.append(charter_id)
            charter_updates += 1
        
        if employee_id and not current_employee:
            updates.append("employee_id = %s")
            values.append(employee_id)
            employee_updates += 1
        
        if updates:
            values.append(receipt_id)
            sql = f"UPDATE receipts SET {', '.join(updates)} WHERE receipt_id = %s"
            cur.execute(sql, values)
    
    conn.commit()
    print(f"\n✅ Updates committed!")
    print(f"  - Reserve numbers set: {reserve_updates:,}")
    print(f"  - Charter IDs set: {charter_updates:,}")
    print(f"  - Employee IDs set: {employee_updates:,}")
    
    # Verify final state
    print("\nVerifying final state...")
    cur.execute("""
        SELECT 
            COUNT(*) as total,
            SUM(CASE WHEN charter_id IS NOT NULL THEN 1 ELSE 0 END) as has_charter_id,
            SUM(CASE WHEN reserve_number IS NOT NULL THEN 1 ELSE 0 END) as has_reserve_number,
            SUM(CASE WHEN employee_id IS NOT NULL THEN 1 ELSE 0 END) as has_employee_id
        FROM receipts
        WHERE revenue > 0
    """)
    r = cur.fetchone()
    print(f"Final state: {r[0]:,} revenue receipts")
    print(f"  - With charter_id: {r[1]:,} ({r[1]/r[0]*100:.1f}%)")
    print(f"  - With reserve_number: {r[2]:,} ({r[2]/r[0]*100:.1f}%)")
    print(f"  - With employee_id: {r[3]:,} ({r[3]/r[0]*100:.1f}%)")
    
    cur.close()
    conn.close()

if __name__ == "__main__":
    main()
